In [ ]:
import numpy as np
# NEXT LINE ONLY FOR COLAB!
%tensorflow_version 2.x
import tensorflow as tf
import matplotlib.pyplot as plt
# COMMENT OUT THIS LINE FOR COLAB!
#%matplotlib notebook

In [ ]:
print(tf.__version__)

2.3.0


## Understanding Tensors and Arrays.

In [ ]:
# A NumPy array is an arbitray dimensional matrix to store numbers in
arr = np.reshape(np.arange(9),(3,3))
print(arr)
print(arr.shape)
print("------------------")

# Access dimensions of the shape.
print(arr.shape[0])
print(arr.shape[-1])
print("------------------")

# Reshaping an array.
arr1 = np.reshape(arr, newshape=(9,1))
print(arr1)
arr2 = np.reshape(arr, newshape=(-1,1)) # The -1 makes numpy infer itself the missing dimension.
print(arr2)
print("------------------")

# Indexing allows you to access specific entries of an array.
print(arr[2,1]) # row 2 (third), column 1 (second).
print(arr[1,2]) # row 1 (second), column 2 (third).
print("------------------")

# Slicing allows you to retrieve parts of an array.
print(arr[:,1]) # All rows, collumn 1.
print(arr[0:2,:]) # Rows from 0 (include) to 2 (exclude), all columns. 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
------------------
3
3
------------------
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
------------------
7
5
------------------
[1 4 7]
[[0 1 2]
 [3 4 5]]


In [ ]:
# Thinking in matrices should be familiar from intro math course. 
# But the exact same things work in higher dimensions!
arr = np.reshape(np.arange(27), (3,3,3))
print(arr)
print(arr.shape)
print("------------------")

# Indexing.
print(arr[0,1,2])
print("------------------")

# Slicing.
print(arr[:,2,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
(3, 3, 3)
------------------
5
------------------
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]


In [ ]:
# A tensor is kind of like a numpy array.
# Strictly spreaking tensors are operations. 
# You can't simply make a tensor out of a numpy array just like that...
tensor = tf.Tensor(arr)

TypeError: ignored

In [ ]:
# but luckily there is an in-built function for that
tensor = tf.convert_to_tensor(arr)
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

In [ ]:
# But if you define a tensor as an operation, the tensor will store the corresponding result of this operation.
tensor = tf.multiply(42, arr)
print(arr)
print(tensor)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
tf.Tensor(
[[[   0   42   84]
  [ 126  168  210]
  [ 252  294  336]]

 [[ 378  420  462]
  [ 504  546  588]
  [ 630  672  714]]

 [[ 756  798  840]
  [ 882  924  966]
  [1008 1050 1092]]], shape=(3, 3, 3), dtype=int32)


In [ ]:
# If your variable is a tensor you can use all the normal math 
# operators as '+','-','*','/' and so on.
print(tensor/42)
print(tf.divide(tensor,42)) # That's the same thing.
print(tensor/42+tensor/42)

tf.Tensor(
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]], shape=(3, 3, 3), dtype=float64)
tf.Tensor(
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]], shape=(3, 3, 3), dtype=float64)
tf.Tensor(
[[[ 0.  2.  4.]
  [ 6.  8. 10.]
  [12. 14. 16.]]

 [[18. 20. 22.]
  [24. 26. 28.]
  [30. 32. 34.]]

 [[36. 38. 40.]
  [42. 44. 46.]
  [48. 50. 52.]]], shape=(3, 3, 3), dtype=float64)


In [ ]:
# You can also easily convert a tensor back to nunpy.
print(tensor.numpy())

[[[   0   42   84]
  [ 126  168  210]
  [ 252  294  336]]

 [[ 378  420  462]
  [ 504  546  588]
  [ 630  672  714]]

 [[ 756  798  840]
  [ 882  924  966]
  [1008 1050 1092]]]


## Useful Tensor Operations

In [ ]:
# creating a 'scalar' (also called rank-0 tensor
#meaning a constant single valued tensor without any axes.
scalar = tf.constant(13)
print(scalar)

tf.Tensor(13, shape=(), dtype=int32)


In [ ]:
# you can also create tensor vectors from lists with one axia
vector = tf.constant([1.0, 2.0, 3.0])
print(vector)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [ ]:
# or matrices with two axes
matrix = tf.constant([[1,2],
                      [3,4],
                      [5,6]])
print(matrix)

# of course you can go on creating tensors with an arbitrary number of axes (dimensions)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


Indexing of tensors works like standard Python an NumPy indexing rules. You can also use slicing.
You can also acces the shape of a tensor and reshape it similar to how you would do it in NumPy. 

In [ ]:
a_tensor = tf.constant([[1,2],
                      [3,4],
                      [5,6]])

# accesing shape
print("Original shape of tensor:", a_tensor.shape)
# reshaping
reshaped_tensor = tf.reshape(a_tensor, [-1])
print("New shape:", reshaped_tensor.shape)
# you can also expand dimensions
print(tf.expand_dims(reshaped_tensor, -1).shape)


Original shape of tensor: (3, 2)
New shape: (6,)
(6, 1)


In [ ]:
# more useful operations include stacking
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
print(tf.stack([x, y, z]))
print(tf.stack([x, y, z], axis=1))

# and a lot more...
# read the docs!
# https://www.tensorflow.org/api_docs/python/tf

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# you can easily create tensors containing zeros in any shape
print("zeros")
print(tf.zeros(1))
print(tf.zeros((3,3)))

# or ones
print("\n ones")
print(tf.ones(1))
print(tf.ones((3,3)))

# or random values
print("\n random")
print(tf.random.normal((3,3), mean=0.0, stddev=1.0))
print(tf.random.uniform((3,3)))

zeros
tf.Tensor([0.], shape=(1,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)

 ones
tf.Tensor([1.], shape=(1,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)

 random
tf.Tensor(
[[ 9.7113794e-01  2.7382594e-01 -1.5219488e-03]
 [ 1.7666880e+00  7.5179845e-01  9.0154976e-01]
 [-1.9685163e-01 -5.6315488e-01 -6.7645156e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.81329715 0.6354164  0.01760745]
 [0.8596854  0.05757248 0.07754111]
 [0.22473991 0.38282108 0.41267502]], shape=(3, 3), dtype=float32)


## Tensorflow Variables

Now you have learned how to create constant valued tensors. But if you think ahead, what you will later want to do when implementing a neural network with tensorflow is defining tensors that will be changed a lot throughout running your program. Think back to how a neural network is trained. We first define its weights and then define how these weights are changed so that our network gets better at doing what it is supposed to do.

The recommended way to define model parameters, like for example the weights of a MLP, is to use the build in Tensorflow class tf. Variable.

A tf.Variable represents a tensor whose value can be changed by running operations on it, modifying its values. Higher level libraries like tf.keras use tf.Variable to store model parameters. 

Documentation: https://www.tensorflow.org/guide/variable

In [ ]:
# you can create Variables from tensors
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])



In [ ]:
a = tf.Variable([2.0, 3.0])
print(a)
# you can reassign values but it will stick to the original dtype, float32
a.assign([1, 2]) 
print(a)
# Not allowed as it resizes the variable: 
try:
  a.assign([1.0, 2.0, 3.0])
except Exception as e:
  print(f"{type(e).__name__}: {e}")


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
ValueError: Shapes (2,) and (3,) are incompatible


In [ ]:
# you can also name them
# and you can decide wether your Variable needs or needs not to be trained
step_counter = tf.Variable(1, trainable=False, name="step_counter")
# of course, if we mean to define weights, such a Variable should be trainable
# this becomes important once we talk about automatic differentiation in trainable (Chapter on Gradient Tapes)

## All in all
So this was a basic introduction. The get away message is: You can do most of what you do in NumPy in Tensorflow as well. But as tensorflow is specialized in Deep Learning, you will also learn that it offers a lot more. So stay tuned and go on to the next chapters :)