In [10]:
import numpy as np

In [11]:
sqrs = [x**2 for x in range(0,100)]
np.array(sqrs)

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [12]:
sqrs_even = [x**2 for x in range(0,100) if x%2 == 0]
np.array(sqrs_even)

array([   0,    4,   16,   36,   64,  100,  144,  196,  256,  324,  400,
        484,  576,  676,  784,  900, 1024, 1156, 1296, 1444, 1600, 1764,
       1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096,
       4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396,
       7744, 8100, 8464, 8836, 9216, 9604])

In [ ]:
## Generators

In [45]:
def meow(n):
    num = 1
    while num < n:
        for i in range(num):
            print("Meow ", end='')
        yield ("\n")
        num = num * 2

In [46]:
for item in meow(10):
    print(item)

Meow 

Meow Meow 

Meow Meow Meow Meow 

Meow Meow Meow Meow Meow Meow Meow Meow 



In [79]:
a = np.random.randn(5,5)
a

array([[-2.05917707e+00,  2.24107492e-01, -9.62655846e-01,
        -1.14408466e-03, -1.56445639e+00],
       [-1.37585489e-01, -7.96927139e-01, -8.20367688e-02,
         4.34336414e-01,  7.51847345e-02],
       [-9.02667199e-01,  4.12257316e-01,  2.14606697e-01,
         3.80377179e-01, -4.42667138e-01],
       [-4.84615401e-01,  3.04335818e-01, -1.47234656e-01,
        -7.47953292e-02,  1.41737460e-01],
       [ 3.19283585e-01,  1.18675460e+00,  6.39094334e-01,
         4.42046526e-02, -8.22036877e-02]])

In [80]:
a[:,2]

array([-0.96265585, -0.08203677,  0.2146067 , -0.14723466,  0.63909433])

In [81]:
a[1,2:]

array([-0.08203677,  0.43433641,  0.07518473])

In [82]:
a[a**2 > 0.2] = 42
np.round(a)

array([[42.,  0., 42., -0., 42.],
       [-0., 42., -0.,  0.,  0.],
       [42.,  0.,  0.,  0., -0.],
       [42.,  0., -0., -0.,  0.],
       [ 0., 42., 42.,  0., -0.]])

In [83]:
a[:,2]

array([42.        , -0.08203677,  0.2146067 , -0.14723466, 42.        ])